all: MouseTrap.exe

MouseTrap.res: MouseTrap.rc resource.h
	rc /nologo MouseTrap.rc

MouseTrap.obj: MouseTrap.cpp resource.h
	cl /nologo /c /O1 /GS- MouseTrap.cpp

MouseTrap.exe: MouseTrap.obj MouseTrap.res
	link /nologo /ENTRY:main /NODEFAULTLIB /SUBSYSTEM:WINDOWS MouseTrap.obj MouseTrap.res user32.lib kernel32.lib shell32.lib
	del *.obj
	del *.res

clean:
	del *.obj *.res *.exe
